services:
  contacts.api:
    image: ${DOCKER_REGISTRY-}contactsapi
    build:
      context: .
      dockerfile: Backend/ContactManager.API/Dockerfile
    depends_on:
      contacts.database:
        condition: service_healthy
    ports:
      - "5000:8080"
    networks:
      - my_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  contacts.frontend:
    container_name: contacts.frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - contacts.api
    networks:
      - my_network

  contacts.database:
    image: postgres:latest
    container_name: contacts.database
    environment:
      - POSTGRES_DB=contactsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - contacts-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - my_network

volumes:
  contacts-db:

networks:
  my_network:
    driver: bridge